struct_add:
	gcc ./struct_add.c -o struct_add

file_read_structs:
	gcc ./file_read_structs.c -o file_read_structs

all:
	gcc ./struct_add.c -o struct_add
	gcc ./file_read_structs.c -o file_read_structs
